export default {
  Frontend: {
    HTML: "usedTo",
    CSS: "normal",
    "Javascript (above ES6)": "favourable",
    Tailwind: "normal",
    "React Js": "favourable",
    "React Native": "normal",
    Typescript: "usedTo",
    Jest: "toLearn",
    Redux: "normal",
    "Next Js 13": "toLearn",
  },
  Backend: {
    "Node Js": "favourable",
    "Express Js": "normal",
    Mongoose: "favourable",
    Swagger: "normal",
    JWT: "usedTo",
    Python: "hide",
    MongoDB: "favourable",
    Redis: "toLearn",
  },
  Tools: {
    Git: "favourable",
    Storybook: "favourable",
    Docker: "toLearn",
    Postman: "favourable",
    Jenkins: "usedTo",
    AWS: "toLearn",
  },
};
