export default {
  Frontend: {
    HTML: "usedTo",
    CSS: "normal",
    Javascript: "favourable",
    Tailwind: "normal",
    "React Js": "favourable",
    "React Native": "normal",
    Typescript: "usedTo",
    Redux: "normal",
    "Next Js": "toLearn",
    "NPM / Yarn": "favourable",
  },
  Backend: {
    "Node Js": "favourable",
    "Express Js": "normal",
    Mongoose: "favourable",
    Python: "hide",
    GoLang: "hide",
    MongoDB: "toLearn",
    Redis: "toLearn",
    PostgreSQL: "toLearn",
  },
  Tools: {
    Git: "favourable",
    Storybook: "favourable",
    Docker: "toLearn",
    Postman: "favourable",
    Jenkins: "usedTo",
    AWS: "hide",
    Ngrok: "usedTo",
    Swagger: "usedTo",
    Jest: "usedTo",
    Terraform: "usedTo",
  },
};
